# -*- coding: utf-8 -*-
"""input()_fonksiyonu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1omRh6-T7YgnugZbdKokxCossAi94PuVI
"""

#input() fonksiyonu
#kullanıcıdan girdi almayan bir program sağır bir programdır.
#input( ) fonksiyonu kullanıldığında genellikle kullanıcının klavyeden bir girdi yapmasını bekler.
#input( ) fonksiyonuyla, print( ) fonksiyonuna ihtiyaç duymadan kullanıcıya bilgi verilebilir. Ancak input( ) fonksiyonu kullanılırken kullanıcıdan alınan değer bir değişkene atanmalıdır.

isim=input("İsminizi giriniz: ")
print("Hoş geldin! ",isim)

a=input("1.sayıyı giriniz: ")
b=input("2.sayıyı giriniz: ")
print("sayıların toplamı: ",a+b)
#uygulama bize hatalı bir çıktı vermiştir.
#bu kullanımda her iki değer bir karakter dizisi olarak algılanmış ve Python iki değer üzerinde toplama işlemi yapamadığı için yan yana yazarak birleştirmiştir

print("müjgan"+"şahin")
#Burada yapılan işlemle gerçekte bir toplama işlemi yapılmamış iki argüman birbirleriyle birleştirilmiştir

a=int(input("Bir sayıyı giriniz: "))
#input( ) fonksiyonu, int( ) fonksiyonunun içerisine alınarak girdi sayısal ifadeye çevrilmiştir.

a=int(input("1.sayıyı giriniz: "))
b=int(input("2.sayıyu giriniz: "))
print("sayıların toplamı: ",a+b)
#int() fonksiyonu ile beraber integer ifade yerine string bir değer girilirse hata verir.
#ifadelerden birisi sayısal olup diğer ifade sayıya dönüştürülmezse, sayılarla metinsel ifadeler arasında aritmetiksel işlem yapılamayacağı için hata verecektir.

ön_mesaj= "Sayın "
son_mesaj=" haziran dönemi faturanız: "
abone_no=input("Abone numaranızı giriniz: ")
tüketim=input("Tüketim miktarınızı giriniz: ")
tüketim_tutarı=int(tüketim)*4
mesaj=ön_mesaj+abone_no+" numaralı abonemiz "+son_mesaj+tüketim_tutarı+" TL dir. İyi günler dileriz."
print(mesaj)