# -*- coding: utf-8 -*-
"""part2_örnekler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1irGBkExu92xXgC4759lbVddzU6t_5oNZ
"""

#ekrana “Merhaba Dünya” yazan programı yazınız.
print("Merhaba Dünya")

#Kullanıcıdan ismini alarak merhaba “Ali” şeklinde çıktı veren programı yazınız.
isim=input("İsminizi giriniz: ")
print("Merhaba "+isim)

#Girilen iki sayının toplamını bulan ve ekrana yazdıran programı yazınız.
sayı1=int(input("1.sayıyı giriniz: "))
sayı2=int(input("2.sayıyı giriniz: "))
print("Sayıların toplamı: ",sayı1+sayı2)

#Girilen iki sayının ortalamasını bulan ve ekrana yazdıran programı yazınız.
sayı1=int(input("1.sayıyı giriniz: "))
sayı2=int(input("2.sayıyı giriniz: "))
print("İki sayının ortalaması: ",(sayı1+sayı2)/2)